name: build-nikola-blog
on: 
  push:
    branches:
      - src

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    container:
      image: wrist/jupyterlab-custom
      options: --user root
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate jupyterlite
      run: ./generate_jupyterlite.sh

    - name: Build and Deploy Nikola
      run: | 
        pip install poetry
        poetry install
        git config --global --add safe.directory /__w/wrist.github.io/wrist.github.io
        git fetch origin master --depth 1
        poetry run nikola build && poetry run nikola github_deploy -m 'Nikola auto deploy [ci skip]'
